const table = document.querySelector("#one");
const data = [
    { quality: "Premium Plus",      cpu: "Intel Core i9-12900K", cpuPrice:55000, cpuLink:"https://www.startech.com.bd/intel-12th-gen-i9-12900k-alder-lake-processor",      gpu: "NVIDIA GeForce RTX 3090 Ti", gpuPrice:305000, gpuLink:"https://www.techlandbd.com/asus-rog-strix-lc-geforce-rtx-3090-ti-oc-edition-24gb-gddr6x-graphics-card", ram: "64GB(4*16GB) DDR4-3600", ramPrice:8500*4, ramLink:"https://www.startech.com.bd/apacer-nox-rgb-16gb-ddr4-3600mhz-ram",          ssd: "4TB NVMe",   ssdPrice:64500, ssdLink:"https://www.startech.com.bd/team-mp34q-4tb-ssd",        hdd: "8TB",  hddPrice:26800, hddLink:"https://www.ryanscomputers.com/toshiba-mg08-d-series-7200rpm-8tb-sata-enterprise-hdd",     motherboard: "ASUS ROG Maximus Z690 Extreme",     motherboardPrice:64500, motherboardLink:"https://www.bdshop.com/asus-rog-maximus-z690-hero",                       psu: "Corsair RM1200x 80+ Gold", psuPrice:27500, psuLink:"https://www.startech.com.bd/corsair-rm1200x-shift-1200w-power-supply", case:"Fractal Design Meshify 2 XL",   casePrice:20304, caseLink:"",},
    { quality: "Premium",           cpu: "AMD Ryzen 9 5950X",    cpuPrice:62500, cpuLink:"https://www.startech.com.bd/amd-ryzen-9-5950x-processor",                        gpu: "NVIDIA GeForce RTX 3090 Ti", gpuPrice:305000, gpuLink:"https://www.techlandbd.com/asus-rog-strix-lc-geforce-rtx-3090-ti-oc-edition-24gb-gddr6x-graphics-card", ram: "64GB(4*16GB) DDR4-3600", ramPrice:8500*4, ramLink:"https://www.startech.com.bd/apacer-nox-rgb-16gb-ddr4-3600mhz-ram",          ssd: "2TB NVMe",   ssdPrice:21000, ssdLink:"https://www.startech.com.bd/samsung-990-pro-2tb-ssd",   hdd: "4TB",  hddPrice:18900, hddLink:"https://www.ryanscomputers.com/toshiba-mg08-d-series-4tb-3.5-inch-enterprise-desktop-hdd", motherboard: "ASUS ROG Strix X570-E Gaming WiFi", motherboardPrice:37000, motherboardLink:"https://www.bdshop.com/asus-rog-strix-x570-f-motherboard",                psu: "Corsair RM1000x 80+ Gold", psuPrice:27500, psuLink:"https://www.startech.com.bd/corsair-rm1000x-1000-watts-power-supply",  case:"Fractal Design Meshify 2 XL",   casePrice:20304, caseLink:"",},
    { quality: "Professional Plus", cpu: "Intel Core i7-12700K", cpuPrice:38000, cpuLink:"https://www.startech.com.bd/intel-12th-gen-core-i7-12700k-alder-lake-processor", gpu: "NVIDIA GeForce RTX 3080 Ti", gpuPrice:240000, gpuLink:"https://www.techlandbd.com/asus-rog-strix-lc-rtx-3080-ti-oc-graphics-card",                             ram: "32GB(4* 8GB) DDR4-3600", ramPrice:3975*4, ramLink:"https://www.startech.com.bd/corsair-vengeance-rgb-rs-8gb-ddr4-3600mhz-ram", ssd: "2TB NVMe",   ssdPrice:21000, ssdLink:"https://www.startech.com.bd/samsung-990-pro-2tb-ssd",   hdd: "4TB",  hddPrice:18900, hddLink:"https://www.ryanscomputers.com/toshiba-mg08-d-series-4tb-3.5-inch-enterprise-desktop-hdd", motherboard: "ASUS ROG Strix Z690-E Gaming WiFi", motherboardPrice:50500, motherboardLink:"https://www.bdshop.com/asus-rog-strix-z690-e-motherboard",                psu: "Corsair RM850x  80+ Gold", psuPrice:27500, psuLink:"https://www.startech.com.bd/corsair-rm850x-power-supply",              case:"Fractal Design Meshify C XL",   casePrice:20304, caseLink:"",},
    { quality: "Professional",      cpu: "AMD Ryzen 7 5800X",    cpuPrice:26500, cpuLink:"https://www.startech.com.bd/amd-ryzen-7-5800x-processor",                        gpu: "NVIDIA GeForce RTX 3070 Ti", gpuPrice:112000, gpuLink:"https://www.ultratech.com.bd/asus-rog-strix-geforce-rtx-3070-ti-oc-edition-8gb-gddr6x-graphics-card",   ram: "32GB(4* 8GB) DDR4-3600", ramPrice:3975*4, ramLink:"https://www.startech.com.bd/corsair-vengeance-rgb-rs-8gb-ddr4-3600mhz-ram", ssd: "1TB NVMe",   ssdPrice:13500, ssdLink:"https://www.startech.com.bd/samsung-990-pro-1tb-ssd",   hdd: "2TB",  hddPrice:7200,  hddLink:"https://www.startech.com.bd/seagate-barracuda-2tb-7200rpm-hdd",                            motherboard: "ASUS ROG Strix B550-F Gaming",      motherboardPrice:19200, motherboardLink:"https://www.bdshop.com/asus-rog-strix-b550-f-gaming-am4-atx-motherboard", psu: "Corsair RM750x  80+ Gold", psuPrice:27500, psuLink:"https://www.startech.com.bd/corsair-rm750x-power-supply",              case:"Fractal Design Meshify C XL",   casePrice:20304, caseLink:"",},
    { quality: "Basic Plus",        cpu: "Intel Core i5-12400F", cpuPrice:18000, cpuLink:"https://www.startech.com.bd/intel-12th-gen-core-i5-12400f-alder-lake-processor", gpu: "NVIDIA GeForce RTX 3060 Ti", gpuPrice:62000,  gpuLink:"https://www.startech.com.bd/asus-dual-geforce-rtx-3060-ti-oc-edition-8gb-gddr6x-graphics-card",         ram: "16GB(2* 8GB) DDR4-3600", ramPrice:3975*2, ramLink:"https://www.startech.com.bd/corsair-vengeance-rgb-rs-8gb-ddr4-3600mhz-ram", ssd: "1TB NVMe",   ssdPrice:13500, ssdLink:"https://www.startech.com.bd/samsung-990-pro-1tb-ssd",   hdd: "None", hddPrice:0,     hddLink:"",                                                                                         motherboard: "MSI B660M-A PRO",                   motherboardPrice:19700, motherboardLink:"https://www.techlandbd.com/msi-pro-b660m-a-wifi-ddr4-motherboard",        psu: "Corsair RM650x  80+ Gold", psuPrice:27500, psuLink:"https://www.startech.com.bd/corsair-rm650x-power-supply",              case:"Fractal Design Meshify C Mini", casePrice:20304, caseLink:"",},
    { quality: "Basic",             cpu: "AMD Ryzen 5 5600X",    cpuPrice:19500, cpuLink:"https://www.startech.com.bd/amd-ryzen-5-5600x-processor",                        gpu: "NVIDIA GeForce RTX 3050",    gpuPrice:46800,  gpuLink:"https://www.startech.com.bd/asus-dual-geforce-rtx-3050-8gb-graphics-card",                              ram: "16GB(2* 8GB) DDR4-3600", ramPrice:3975*2, ramLink:"https://www.startech.com.bd/corsair-vengeance-rgb-rs-8gb-ddr4-3600mhz-ram", ssd: "500GB NVMe", ssdPrice:7700,  ssdLink:"https://www.startech.com.bd/samsung-980-pro-500gb-ssd", hdd: "None", hddPrice:0,     hddLink:"",                                                                                         motherboard: "MSI B5500-A PRO",                   motherboardPrice:16800, motherboardLink:"https://www.ultratech.com.bd/msi-b550-a-pro-am4-amd-atx-motherboard",     psu: "Corsair RM550x  80+ Gold", psuPrice:27500, psuLink:"https://www.startech.com.bd/corsair-rm550x-power-supply",              case:"Fractal Design Meshify C",      casePrice:20304, caseLink:"https://www.ubuy.com.bd/en/product/2F9Q8X9S-fractal-design-meshify-mini-c-tempered-glass",},
];
for (let row of data) {
    let tr = document.createElement("tr");
    tr.innerHTML = `
        <td>${row.quality}<br>BDT : ${row.cpuPrice+row.gpuPrice+row.ssdPrice+row.hddPrice+row.motherboardPrice+row.ramPrice+row.psuPrice+row.casePrice}</td>
        <td>${row.cpu}<br>BDT :<a href="${row.cpuLink}" target="_blank">${row.cpuPrice}</a></td>
        <td>${row.gpu}<br>BDT : <a href="${row.gpuLink}" target="_blank">${row.gpuPrice}</a></td>
        <td>${row.ram}<br>BDT : <a href="${row.ramLink}" target="_blank">${row.ramPrice}</a></td>
        <td>${row.ssd}<br>BDT : <a href="${row.ssdLink}" target="_blank">${row.ssdPrice}</a></td>
        <td>${row.hdd}<br>BDT : <a href="${row.hddLink}" target="_blank">${row.hddPrice}</a></td>
        <td>${row.motherboard}<br>BDT : <a href="${row.motherboardLink}" target="_blank">${row.motherboardPrice}</a></td>
        <td>${row.psu}<br>BDT : <a href="${row.psuLink}" target="_blank">${row.psuPrice}</a></td>
        <td>${row.case}<br>BDT : <a href="${row.caseLink}" target="_blank">${row.casePrice}</a></td>
    `;
    table.appendChild(tr);
};